{"uuid": "c813d3bd-6473-48d8-95bc-151574bc2a2e", "children": ["fdb8c47e-0354-4eff-82e9-c87a3665b9bc"], "befores": [{"name": "api", "status": "broken", "statusDetails": {"message": "TypeError: auth() takes 0 positional arguments but 1 was given\n", "trace": "  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/conftest.py\", line 115, in api\n    return Api(token, base_url)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/apis/api.py\", line 7, in __init__\n    super().__init__(token, base_url)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/apis/base_api.py\", line 24, in __init__\n    self.auth()\n"}, "start": 1658143930123, "stop": 1658143930123}], "start": 1658143930123, "stop": 1658143930130}