{"name": "test_get_contract_list", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1146, \"Table 'monica.contracts' doesn't exist\")", "trace": "self = <test_contracts.TestMonicaContractsApi object at 0x10463c7f0>\nbase_url = 'http://localhost:8080'\nsession = <requests.sessions.Session object at 0x10487cb50>\ndb = <utils.mysql_utils.MysqlUtils object at 0x10487c3a0>\n\n    @allure.story(\"获取联系人列表\")\n    def test_get_contract_list(self, base_url, session, db):\n        url = f'{base_url}/api/contacts'\n        res = session.get(url)\n        pprint(res.json())\n>       result = db.query('select count(id) from contracts')\n\ntest_contracts.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../utils/mysql_utils.py:18: in query\n    self.cur.execute(sql)\n../venv/lib/python3.9/site-packages/pymysql/cursors.py:148: in execute\n    result = self._query(query)\n../venv/lib/python3.9/site-packages/pymysql/cursors.py:310: in _query\n    conn.query(q)\n../venv/lib/python3.9/site-packages/pymysql/connections.py:548: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n../venv/lib/python3.9/site-packages/pymysql/connections.py:775: in _read_query_result\n    result.read()\n../venv/lib/python3.9/site-packages/pymysql/connections.py:1156: in read\n    first_packet = self.connection._read_packet()\n../venv/lib/python3.9/site-packages/pymysql/connections.py:725: in _read_packet\n    packet.raise_for_error()\n../venv/lib/python3.9/site-packages/pymysql/protocol.py:221: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xffz\\x04#42S02Table 'monica.contracts' doesn't exist\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        errval = data[9:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.ProgrammingError: (1146, \"Table 'monica.contracts' doesn't exist\")\n\n../venv/lib/python3.9/site-packages/pymysql/err.py:143: ProgrammingError"}, "attachments": [{"name": "log", "source": "31fa3ba6-5270-46cb-8a50-aebc8cfaafd1-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "48614409-1da6-44f5-9924-87bc8eb604ec-attachment.txt", "type": "text/plain"}], "start": 1656777981829, "stop": 1656777981944, "uuid": "6f1e470c-87cf-4094-b955-9dc3707dd475", "historyId": "9dc13b40bab1dd519bd442d390105929", "testCaseId": "7ce73d698bea21fc6ba273aa3e3d3450", "fullName": "testcases.test_contracts.TestMonicaContractsApi#test_get_contract_list", "labels": [{"name": "story", "value": "获取联系人列表"}, {"name": "feature", "value": "联系人管理"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_contracts"}, {"name": "subSuite", "value": "TestMonicaContractsApi"}, {"name": "host", "value": "SUPERHINHAN-MB0"}, {"name": "thread", "value": "85823-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_contracts"}]}